@baseUrl = https://api.artsy.net/api/artworks
@tokenUrl = https://api.artsy.net/api/tokens/xapp_token?client_id=fc789482f420f5a617e1&client_secret=90bf0796a886f44bcb6a158cc2163390


POST {{tokenUrl}}


###

# GET ALL THE ART
GET {{baseUrl}}/ 

###

# GET A SINGLE ARTÍ
@artId = 516dfb9ab31e2b2270000c45

GET https://api.artsy.net/api/artworks/{{artId}}
X-Xapp-Token: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IiIsInN1YmplY3RfYXBwbGljYXRpb24iOiI2MDk5MmZjMGZhYjA2MTAwMTQ5OWMzZjYiLCJleHAiOjE2MjEyNTY3NjksImlhdCI6MTYyMDY1MTk2OSwiYXVkIjoiNjA5OTJmYzBmYWIwNjEwMDE0OTljM2Y2IiwiaXNzIjoiR3Jhdml0eSIsImp0aSI6IjYwOTkyZmMxODUwMGMwMDAwZmQyNjI1MCJ9.qPDq318iVJigLSVnGWM1E7wVAq68fOzxmCgE62HwHv8
